version: "3.7"
services:
  db:
    container_name: timescale
    image: timescale/timescaledb:latest-pg12
    restart: always
    environment:
      POSTGRES_USER: test_user
      POSTGRES_PASSWORD: test_password
      POSTGRES_DB: test_db
    ports:
      - "5432:5432"
    volumes:
      - type: volume
        source: timescale_volume
        target: /var/lib/postgresql/data
        read_only: false
volumes:
  timescale_volume:
